name: Sanity checks

on: push

env:
  TEST_DIR: test

jobs:
  installDependenciesAndTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
# TODO
